url: ""
baseurl: http://ramosmd.github.io

# Site settings
title: Ramos MD
subtitle: Marcia Dias Ramos
email: virtua.creative@gmail.com
description: "Marcia Dias Ramos: Web Developer | Web Designer | Photographer | Blogger | Admin | Chemist."
keywords: freelancer, writter, escritora, blogger, escrever blog, web developer, web designer, curitiba, quatro-barras, fazer websites, websites, pessoa para fazer websites

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 086FA1 #blue # rgb 8,111,161
  secondary: 06567D #darker blue
  secondary-dark: 333
  terciary: FFBA6B # yellow-orange

# Team names, titles and social links
people:
- name: Marcia Ramos
  pic: 1
  position: Web Developer | Web Designer | Photographer
  social:
    - title: google-plus # fontawesome icons
      url: https://plus.google.com/+MarciaDiasRamosMD/about
    - title: facebook # fontawesome icons
      url: https://www.facebook.com/marciaramosmdr
    - title: github-alt # fontawesome icons
      url: http://github.com/ramosmd

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus # fontawesome icons
    url: https://plus.google.com/+MarciaDiasRamosMD/about
  - title: facebook # fontawesome icons
    url: https://www.facebook.com/marciaramosmdr
  - title: github-alt # fontawesome icons
    url: http://github.com/ramosmd

collections:
  web:
    permalink: /web/:path/
  art:
    permalink: /art/:path/
  written:
    permalink: /written/:path/

# Build settings
markdown: kramdown
permalink: pretty